// CISSP Prep — Flashcards (200 cards, 25 per domain)
// Format: d = domain (1-8), f = front (term/question), b = back (definition/answer)
const FLASHCARDS = [
  // Domain 1 — Security & Risk Management (25)
  {d:1, f:"CIA Triad", b:"Confidentiality (prevent unauthorized disclosure), Integrity (prevent unauthorized modification), Availability (ensure reliable, timely access). The three pillars of security."},
  {d:1, f:"DAD Triad", b:"The opposite of CIA: Disclosure, Alteration, Destruction — the three failures security aims to prevent."},
  {d:1, f:"SLE (Single Loss Expectancy)", b:"Expected loss from ONE occurrence of a risk. SLE = Asset Value (AV) × Exposure Factor (EF)."},
  {d:1, f:"ARO (Annualized Rate of Occurrence)", b:"How many times a threat is expected to occur per year. Once every 5 years = 0.2."},
  {d:1, f:"ALE (Annualized Loss Expectancy)", b:"Expected yearly loss from a risk. ALE = SLE × ARO. Used to justify control spending: a control is worthwhile if it costs less than the ALE reduction."},
  {d:1, f:"Due Care vs. Due Diligence", b:"Due care = DOING what a reasonable person would do (acting; 'Do Correct'). Due diligence = investigating and understanding risks before acting ('Do Detect')."},
  {d:1, f:"Risk Appetite / Tolerance", b:"Appetite: the amount of risk an organization is willing to accept in pursuit of its goals. Tolerance: acceptable variance around that level."},
  {d:1, f:"Four Risk Responses", b:"Mitigate (reduce with controls), Transfer/Share (insurance, outsourcing), Accept (formally acknowledge and proceed), Avoid (stop the risky activity)."},
  {d:1, f:"Residual Risk", b:"Risk remaining after controls are applied. Must be formally accepted by senior management. Total risk − countermeasures = residual risk."},
  {d:1, f:"Policy vs. Standard vs. Guideline vs. Procedure", b:"Policy: mandatory high-level management intent. Standard: mandatory specific requirement (e.g., AES-256). Guideline: recommended, optional. Procedure: mandatory step-by-step instructions."},
  {d:1, f:"STRIDE", b:"Microsoft threat model: Spoofing, Tampering, Repudiation, Information disclosure, Denial of service, Elevation of privilege."},
  {d:1, f:"Control Categories (by type)", b:"Administrative/Managerial (policies, training), Technical/Logical (firewalls, encryption), Physical (locks, guards, fences)."},
  {d:1, f:"Control Functions", b:"Preventive (stop incidents), Detective (find incidents), Corrective (fix after), Deterrent (discourage), Recovery (restore), Compensating (alternative when primary isn't feasible), Directive (mandate behavior)."},
  {d:1, f:"Separation of Duties", b:"Splitting critical tasks among multiple people so no one person can commit fraud alone. Related: two-person control, job rotation, mandatory vacations (detect fraud)."},
  {d:1, f:"(ISC)² Code of Ethics — 4 Canons (in order)", b:"1) Protect society, the common good, and infrastructure. 2) Act honorably, honestly, justly, responsibly, legally. 3) Provide diligent and competent service to principals. 4) Advance and protect the profession."},
  {d:1, f:"BIA (Business Impact Analysis)", b:"Identifies critical business functions and quantifies impact of disruption. Produces prioritization, MTD, RTO, and RPO values that drive BCP/DR planning."},
  {d:1, f:"MTD / RTO / RPO", b:"MTD: max tolerable downtime before the business fails. RTO: target time to restore systems (RTO ≤ MTD). RPO: max acceptable data loss measured in time (drives backup frequency)."},
  {d:1, f:"GDPR key points", b:"EU privacy regulation: lawful basis for processing, data subject rights (access, erasure, portability), 72-hour breach notification, fines up to 4% of global revenue. Controller decides purpose; processor acts on instructions."},
  {d:1, f:"HIPAA / PCI DSS / SOX / GLBA", b:"HIPAA: US health data (PHI). PCI DSS: payment card data (contractual, not law). SOX: financial reporting integrity for public companies. GLBA: financial institutions' customer data."},
  {d:1, f:"Patent vs. Copyright vs. Trademark vs. Trade Secret", b:"Patent: inventions, ~20 yrs, public disclosure. Copyright: creative works, life+70 yrs. Trademark: brand identity (logos, names). Trade secret: confidential business info, protected indefinitely while secret."},
  {d:1, f:"ISO 27001 vs. 27002", b:"27001: requirements for an Information Security Management System (ISMS) — certifiable. 27002: code of practice with control guidance — not certifiable."},
  {d:1, f:"NIST CSF Functions", b:"Govern, Identify, Protect, Detect, Respond, Recover — high-level cybersecurity framework functions (CSF 2.0)."},
  {d:1, f:"Qualitative vs. Quantitative Risk Analysis", b:"Qualitative: subjective ratings (high/medium/low), risk matrix, faster. Quantitative: numeric (SLE/ALE, dollars), supports cost-benefit analysis, needs more data."},
  {d:1, f:"Threat Actor Types", b:"Script kiddies (low skill), hacktivists (ideology), organized crime (profit), nation-state/APT (espionage, persistent, well-funded), insiders (authorized access — often most damaging)."},
  {d:1, f:"Security Governance", b:"The framework aligning security with business strategy: senior management sets direction and is ultimately accountable; security supports the mission, not the reverse."},

  // Domain 2 — Asset Security (25)
  {d:2, f:"Data Owner", b:"Senior/business role accountable for specific data: assigns classification, approves access, sets protection requirements. Cannot delegate accountability."},
  {d:2, f:"Data Custodian", b:"Implements day-to-day protection on the owner's behalf: backups, patching, applying permissions and controls."},
  {d:2, f:"Data Steward", b:"Manages data quality, metadata, and business context — governance-focused role ensuring data is fit for use."},
  {d:2, f:"Data Controller vs. Data Processor", b:"Controller determines purposes and means of processing personal data. Processor processes data on the controller's documented instructions (e.g., a cloud provider)."},
  {d:2, f:"Data Subject", b:"The identifiable person the personal data is about — holder of privacy rights (access, correction, erasure)."},
  {d:2, f:"Government Classification Levels", b:"Top Secret (exceptionally grave damage), Secret (serious damage), Confidential (damage), then Unclassified (may be CUI/FOUO). Clearance + need-to-know required."},
  {d:2, f:"Commercial Classification Levels", b:"Typical scheme: Confidential/Proprietary (highest), Private (personal/internal), Sensitive, Public. Labels vary — protection follows classification."},
  {d:2, f:"Data Lifecycle", b:"Create → Store → Use → Share → Archive → Destroy. Security requirements apply at every phase; classification is assigned at creation."},
  {d:2, f:"Data Remanence", b:"Residual data recoverable from media after deletion or formatting. Countered by proper sanitization: overwrite, degauss, crypto erase, or physical destruction."},
  {d:2, f:"NIST 800-88: Clear / Purge / Destroy", b:"Clear: logical overwrite, defeats casual recovery. Purge: defeats laboratory recovery (degauss, crypto erase), media may be reused. Destroy: physical destruction, media unusable."},
  {d:2, f:"Degaussing", b:"Strong magnetic field erases magnetic media (HDDs, tapes). Useless against SSDs and optical media; typically renders drives unusable."},
  {d:2, f:"Cryptographic Erase (Crypto-shredding)", b:"Destroy the encryption keys of encrypted media so the data is permanently unrecoverable. Fast; ideal for SSDs and cloud where physical destruction isn't possible."},
  {d:2, f:"Why overwriting SSDs is unreliable", b:"Wear-leveling remaps writes, so overwrite passes can miss cells. Use crypto erase, the vendor's sanitize command, or physical destruction."},
  {d:2, f:"Data States", b:"At rest (stored — disk/full-disk encryption), in transit (moving — TLS/IPsec), in use (being processed — enclaves, homomorphic encryption)."},
  {d:2, f:"Tokenization", b:"Replace sensitive values with meaningless tokens; the real values live in a secure token vault. Common for payment card data — reduces PCI scope."},
  {d:2, f:"Data Masking", b:"Obscuring sensitive data (e.g., ****-1234) for display, testing, or training while preserving format. Static or dynamic."},
  {d:2, f:"Anonymization vs. Pseudonymization", b:"Anonymization: irreversible removal of identifiers — no longer personal data. Pseudonymization: reversible substitution with a lookup key — still regulated under GDPR."},
  {d:2, f:"DRM / IRM", b:"Digital/Information Rights Management: persistent controls that travel with a file — block printing, forwarding, copying; set expiration; require authentication to open."},
  {d:2, f:"DLP (Data Loss Prevention)", b:"Detects and blocks sensitive data leaving via email, web, endpoints, or cloud. Network DLP (egress), endpoint DLP, and discovery (data at rest scanning)."},
  {d:2, f:"Data Retention", b:"Keep data only as long as legally/business required, then dispose securely. Over-retention increases breach liability and legal discovery exposure."},
  {d:2, f:"Data Sovereignty / Localization", b:"Data is subject to the laws of the country where it resides; localization laws require certain data to stay in-country — a key cloud design constraint."},
  {d:2, f:"Scoping and Tailoring", b:"Scoping: removing baseline controls that don't apply. Tailoring: customizing/parameterizing remaining controls to fit the environment (e.g., NIST 800-53 baselines)."},
  {d:2, f:"Security Baseline", b:"Minimum standard configuration/control set for a system type (e.g., CIS Benchmarks). Starting point — adjusted via scoping and tailoring."},
  {d:2, f:"Data Labeling and Handling", b:"Marking media/files with classification (headers, footers, physical labels) so people and systems apply correct handling: storage, transmission, sharing, destruction rules."},
  {d:2, f:"Asset Inventory", b:"Complete record of hardware, software, and data assets with owners. Prerequisite for classification, patching, monitoring, and risk management — you can't protect what you don't know about."},

  // Domain 3 — Security Architecture & Engineering (25)
  {d:3, f:"Symmetric Encryption", b:"One shared secret key for encrypt and decrypt. Fast, good for bulk data. Key distribution is the challenge: n(n−1)/2 keys for n parties. Examples: AES, ChaCha20, 3DES."},
  {d:3, f:"Asymmetric Encryption", b:"Public/private key pair. Encrypt with recipient's public key; only their private key decrypts. Solves key distribution; slow — used for key exchange and signatures. Examples: RSA, ECC."},
  {d:3, f:"AES", b:"Advanced Encryption Standard — symmetric block cipher. 128-bit blocks; 128/192/256-bit keys. US government standard; replaced DES/3DES."},
  {d:3, f:"ECC (Elliptic Curve Cryptography)", b:"Asymmetric crypto using elliptic curves. Equivalent security with far smaller keys than RSA (256-bit ECC ≈ 3072-bit RSA) — ideal for mobile/IoT."},
  {d:3, f:"Diffie-Hellman", b:"Key agreement protocol: two parties derive a shared secret over an insecure channel. No authentication by itself — pair with certificates to stop man-in-the-middle."},
  {d:3, f:"Hashing", b:"One-way function producing fixed-length digest (SHA-256). Provides integrity; any input change alters the digest. No key, not reversible, must be collision-resistant."},
  {d:3, f:"Salt", b:"Random value added to each password before hashing. Defeats rainbow tables/precomputation and hides duplicate passwords. Use with slow hashes: bcrypt, scrypt, Argon2, PBKDF2."},
  {d:3, f:"HMAC", b:"Hash-based Message Authentication Code — hash combined with a shared secret key. Provides integrity AND authenticity (but not non-repudiation, since both parties share the key)."},
  {d:3, f:"Digital Signature", b:"Hash the message, encrypt digest with sender's PRIVATE key. Verifier decrypts with sender's public key and compares hashes. Provides integrity, authenticity, non-repudiation."},
  {d:3, f:"PKI Components", b:"CA issues/signs certificates; RA verifies identities; certificates bind public keys to identities (X.509); CRL/OCSP handle revocation."},
  {d:3, f:"CRL vs. OCSP", b:"CRL: downloadable list of revoked certificates — can be stale and large. OCSP: real-time status query for one certificate. OCSP stapling: server attaches a signed status to the TLS handshake."},
  {d:3, f:"Bell-LaPadula Model", b:"CONFIDENTIALITY model. Simple property: no read UP. Star (*) property: no write DOWN. Designed for military classification systems."},
  {d:3, f:"Biba Model", b:"INTEGRITY model — inverse of Bell-LaPadula. Simple: no read DOWN. Star (*): no write UP. Prevents corruption from less-trusted sources."},
  {d:3, f:"Clark-Wilson Model", b:"Commercial integrity model: users access data only through trusted programs (well-formed transactions), with separation of duties. Access triple: subject–program–object."},
  {d:3, f:"Brewer-Nash (Chinese Wall)", b:"Prevents conflicts of interest: once you access one client's data, access to competitors' data is dynamically blocked. Built for consultancies/finance."},
  {d:3, f:"Reference Monitor / Security Kernel", b:"Reference monitor: abstract concept that mediates EVERY access between subjects and objects — tamperproof, always invoked, verifiable. Security kernel: its hardware/software implementation in the TCB."},
  {d:3, f:"TPM vs. HSM", b:"TPM: chip on a motherboard storing keys for that machine (BitLocker, secure boot, attestation). HSM: dedicated appliance/card for enterprise key management and crypto operations at scale."},
  {d:3, f:"Side-Channel Attack", b:"Extracting secrets from physical emanations — timing, power draw, EM, sound — rather than breaking the algorithm. Mitigate with constant-time code, shielding."},
  {d:3, f:"Covert Channel", b:"Unauthorized communication path not designed for data transfer. Storage channel (shared storage) or timing channel (modulating system behavior)."},
  {d:3, f:"Common Criteria", b:"ISO 15408 evaluation framework. TOE: product evaluated. Protection Profile: customer requirements. Security Target: vendor claims. EAL 1-7: depth of evaluation (7 = formally verified)."},
  {d:3, f:"Zero Trust", b:"'Never trust, always verify.' No implicit trust from network location; authenticate and authorize every request; least privilege; microsegmentation; assume breach."},
  {d:3, f:"Fail Safe vs. Fail Secure", b:"Fail safe/open: on failure, protect PEOPLE (doors unlock for evacuation). Fail secure/closed: on failure, protect ASSETS (doors stay locked, firewall blocks all). Life safety always wins."},
  {d:3, f:"CPTED", b:"Crime Prevention Through Environmental Design: natural surveillance (sight lines, lighting), natural access control (paths, landscaping), territorial reinforcement (signage, boundaries)."},
  {d:3, f:"Fire Classes and Suppression", b:"A: combustibles (water). B: liquids (foam/CO2). C: electrical (CO2/clean agent). D: metals (dry powder). K: kitchen oils. Data centers: clean agent (FM-200/inert gas) — safe for people and electronics."},
  {d:3, f:"Kerckhoffs's Principle", b:"A cryptosystem must remain secure even if everything about it except the key is public. Security through obscurity is not security."},

  // Domain 4 — Communication & Network Security (25)
  {d:4, f:"OSI Model — 7 Layers", b:"1 Physical, 2 Data Link (MAC, switches), 3 Network (IP, routers), 4 Transport (TCP/UDP), 5 Session, 6 Presentation (encryption/format), 7 Application. 'Please Do Not Throw Sausage Pizza Away.'"},
  {d:4, f:"TCP vs. UDP", b:"TCP: connection-oriented, three-way handshake (SYN, SYN-ACK, ACK), reliable ordered delivery. UDP: connectionless, best-effort, fast — streaming, DNS queries, VoIP."},
  {d:4, f:"Common Ports", b:"FTP 20/21, SSH 22, Telnet 23, SMTP 25, DNS 53, HTTP 80, Kerberos 88, POP3 110, NTP 123, IMAP 143, SNMP 161, LDAP 389, HTTPS 443, SMB 445, LDAPS 636, RDP 3389."},
  {d:4, f:"IPsec: AH vs. ESP", b:"AH: integrity + authentication, NO encryption (breaks with NAT). ESP: encryption + integrity + authentication. Transport mode protects payload; tunnel mode protects entire packet (site-to-site VPNs)."},
  {d:4, f:"TLS Handshake (essence)", b:"Server authenticates with certificate (asymmetric); parties agree on cipher suite and establish a symmetric session key; bulk data then uses fast symmetric encryption."},
  {d:4, f:"Firewall Generations", b:"Packet filter (stateless ACLs) → Stateful (tracks connections) → Application/proxy (understands protocols) → NGFW (deep packet inspection, IPS, app awareness, identity)."},
  {d:4, f:"DMZ / Screened Subnet", b:"Buffer network between Internet and internal LAN hosting public-facing servers (web, mail). Compromise of a DMZ host doesn't directly expose the internal network."},
  {d:4, f:"NAT / PAT", b:"Network Address Translation maps private RFC 1918 addresses (10/8, 172.16/12, 192.168/16) to public IPs. PAT multiplexes many hosts through one IP using ports. Hides internal topology."},
  {d:4, f:"VLAN", b:"Logical Layer 2 segmentation on switches — separates broadcast domains and isolates traffic without separate hardware. Attack: VLAN hopping (mitigate: disable auto-trunking, unused ports off)."},
  {d:4, f:"ARP Poisoning", b:"Attacker sends forged ARP replies to redirect LAN traffic through their machine (on-path/MITM). Defenses: Dynamic ARP Inspection, DHCP snooping, static ARP for critical hosts."},
  {d:4, f:"SYN Flood", b:"DoS exploiting the TCP handshake: attacker sends SYNs, never completes, exhausting the half-open connection table. Mitigations: SYN cookies, rate limiting, connection timeouts."},
  {d:4, f:"DDoS Amplification", b:"Attacker spoofs the victim's IP in small queries to open UDP services (DNS, NTP, memcached) that return large responses — multiplying attack bandwidth toward the victim."},
  {d:4, f:"DNSSEC vs. DoH/DoT", b:"DNSSEC: signs DNS records — authenticity/integrity, no confidentiality. DoH/DoT: encrypts DNS queries in transit — confidentiality, no record authentication. Complementary."},
  {d:4, f:"802.1X", b:"Port-based network access control. Supplicant (client) → Authenticator (switch/AP) → Authentication Server (RADIUS). Uses EAP; blocks network access until authenticated."},
  {d:4, f:"RADIUS vs. TACACS+", b:"RADIUS: UDP 1812/1813, encrypts only the password, combines AAA. TACACS+ (Cisco): TCP 49, encrypts entire payload, separates authentication/authorization/accounting — better for device administration."},
  {d:4, f:"Wi-Fi Security Evolution", b:"WEP (broken RC4) → WPA (TKIP, interim) → WPA2 (AES-CCMP) → WPA3 (SAE handshake resists offline dictionary attacks; forward secrecy). Enterprise modes use 802.1X."},
  {d:4, f:"Bluejacking vs. Bluesnarfing", b:"Bluejacking: sending unsolicited Bluetooth messages (nuisance). Bluesnarfing: unauthorized ACCESS and data theft from a Bluetooth device (serious)."},
  {d:4, f:"Proxy Types", b:"Forward proxy: fronts internal clients going out (filtering, caching). Reverse proxy: fronts servers for inbound traffic (load balancing, TLS termination, WAF placement)."},
  {d:4, f:"IDS vs. IPS", b:"IDS: detects and alerts (out-of-band/passive). IPS: inline, actively blocks. Detection methods: signature-based (known patterns) vs. anomaly/behavior-based (deviations from baseline — catches novel attacks, more false positives)."},
  {d:4, f:"SDN (Software-Defined Networking)", b:"Separates control plane (centralized controller making decisions) from data plane (devices forwarding packets). Enables programmable, dynamic network policy; controller is a high-value target."},
  {d:4, f:"Microsegmentation", b:"Granular per-workload security zones with policies on every east-west flow. Core zero-trust technique — contains lateral movement after a breach."},
  {d:4, f:"VPN Protocols", b:"IPsec (network layer, site-to-site and remote access), TLS VPN (easier through firewalls/NAT), WireGuard (modern, lean). Avoid PPTP — broken."},
  {d:4, f:"IPv6 Security Notes", b:"128-bit addresses; IPsec support built in; no NAT needed; risks: unmonitored dual-stack/tunneling bypassing IPv4-only controls, SLAAC spoofing (use RA Guard)."},
  {d:4, f:"Converged Protocols", b:"Storage/voice over Ethernet-IP: FCoE, iSCSI, VoIP. Risk: critical traffic on shared networks — isolate with VLANs/VSANs, encrypt, apply QoS."},
  {d:4, f:"Smurf / Fraggle Attacks", b:"Smurf: spoofed-source ICMP echo to a broadcast address — all hosts flood the victim. Fraggle: same with UDP. Defense: block directed broadcasts, ingress filtering (BCP 38)."},

  // Domain 5 — Identity & Access Management (25)
  {d:5, f:"IAAA", b:"Identification (claim identity), Authentication (prove it), Authorization (what you may do), Accountability (audit trail ties actions to you)."},
  {d:5, f:"Authentication Factors", b:"Something you KNOW (password/PIN), HAVE (token, smart card, phone), ARE (biometrics). Plus: somewhere you are (location), something you do (behavior). True MFA = different factor TYPES."},
  {d:5, f:"FAR / FRR / CER", b:"FAR (Type II): imposters accepted — most dangerous. FRR (Type I): legit users rejected. CER/EER: where FAR=FRR — lower CER = more accurate biometric system."},
  {d:5, f:"Kerberos", b:"SSO protocol using symmetric crypto and tickets. KDC = Authentication Server (issues TGT) + Ticket Granting Service (issues service tickets). Requires time sync (~5 min); port 88."},
  {d:5, f:"Golden / Silver Ticket Attacks", b:"Golden: forge TGTs using the stolen KRBTGT account hash — total domain compromise. Silver: forge service tickets with a service account hash — access to that service."},
  {d:5, f:"Pass-the-Hash", b:"Authenticating with a stolen password HASH without cracking it (NTLM). Mitigate: disable NTLM where possible, credential guard, privileged access workstations, LAPS."},
  {d:5, f:"SAML", b:"XML standard for federated web SSO. Identity Provider (IdP) authenticates users and issues signed assertions; Service Provider (SP) trusts them and grants access."},
  {d:5, f:"OAuth 2.0 vs. OpenID Connect", b:"OAuth 2.0: delegated AUTHORIZATION ('this app may read my calendar'). OIDC: authentication layer on top of OAuth — ID token (JWT) proves WHO the user is."},
  {d:5, f:"Federation", b:"Trust arrangement letting users authenticate with their home organization's identity across organizational boundaries (SAML/OIDC). No duplicate accounts at each provider."},
  {d:5, f:"SSO — Benefit and Risk", b:"Benefit: one strong credential, less password fatigue, central control. Risk: keys to the kingdom — one compromise opens everything. Mitigate with MFA and session controls."},
  {d:5, f:"DAC (Discretionary Access Control)", b:"Resource OWNER decides who gets access (NTFS permissions, Unix modes). Flexible but inconsistent; vulnerable to Trojan horses acting with the user's rights."},
  {d:5, f:"MAC (Mandatory Access Control)", b:"System-enforced access via security labels and clearances; owners cannot override. Used in military/high-security systems (SELinux). Bell-LaPadula/Biba formalize it."},
  {d:5, f:"RBAC (Role-Based Access Control)", b:"Permissions attach to roles; users get roles matching job functions. Scales well, simplifies provisioning and reviews. Best practice for enterprises."},
  {d:5, f:"ABAC (Attribute-Based Access Control)", b:"Policy engine evaluates attributes of subject, object, action, environment (department, device health, time, location). Fine-grained, contextual — the zero-trust access model."},
  {d:5, f:"Rule-Based Access Control", b:"Global rules applied to everyone uniformly regardless of identity — e.g., firewall ACLs, time-of-day restrictions."},
  {d:5, f:"Need to Know vs. Least Privilege", b:"Least privilege: minimum RIGHTS/permissions to do the job. Need to know: access to specific INFORMATION only when required — even with clearance, no automatic access."},
  {d:5, f:"Privilege Creep", b:"Accumulating permissions through role changes without revoking old ones. Violates least privilege. Fix: periodic access reviews/recertification, automated deprovisioning."},
  {d:5, f:"Identity Lifecycle", b:"Provisioning (create with proofing) → changes/transfers (adjust access) → periodic review/recertification → deprovisioning (immediate revocation at termination)."},
  {d:5, f:"Identity Proofing", b:"Verifying a person is who they claim BEFORE issuing credentials — documents, background checks, knowledge verification. Registration phase of the identity lifecycle."},
  {d:5, f:"PAM (Privileged Access Management)", b:"Controls for admin accounts: credential vaulting, session recording, check-out/check-in, rotation, approval workflows. Privileged accounts are attackers' top target."},
  {d:5, f:"JIT (Just-in-Time) Access", b:"No standing privileges: elevation granted only for an approved task and time window, then auto-revoked. Shrinks the privileged attack surface dramatically."},
  {d:5, f:"Account Types to Control", b:"Service accounts (machine-to-machine, often over-privileged, rarely monitored), shared accounts (no accountability — avoid), guest accounts (disable), emergency/break-glass accounts (sealed, audited)."},
  {d:5, f:"Session Management", b:"Short token lifetimes, rotation after login, secure cookie flags (HttpOnly, Secure, SameSite), idle timeout, re-authentication for sensitive actions. Limits stolen-session damage."},
  {d:5, f:"Password Attacks", b:"Brute force (all combinations), dictionary (word lists), spraying (one password, many accounts — evades lockout), credential stuffing (reused breach credentials). Defend: MFA, lockout, banned-password lists."},
  {d:5, f:"Capability Table vs. ACL", b:"ACL: attached to the OBJECT — who can access this resource. Capability table: attached to the SUBJECT — what this user can access. Two views of the access matrix."},

  // Domain 6 — Security Assessment & Testing (25)
  {d:6, f:"Vulnerability Scan vs. Penetration Test", b:"Scan: automated identification of potential weaknesses — breadth, frequent, non-exploitative. Pen test: humans actively exploit to demonstrate real impact — depth, periodic."},
  {d:6, f:"Black / White / Gray Box Testing", b:"Black: no knowledge (external attacker simulation). White/crystal: full knowledge, source and diagrams (thorough). Gray: partial knowledge (insider or authenticated user)."},
  {d:6, f:"Rules of Engagement", b:"Written pen test authorization: scope, targets, excluded systems, methods, timing, emergency contacts. Without it, testing is potentially criminal. 'Get out of jail' letter."},
  {d:6, f:"Red / Blue / Purple Teams", b:"Red: offense (simulated attackers). Blue: defense (detection and response). Purple: collaboration loop making both better. White cell: exercise referees."},
  {d:6, f:"Pen Test Phases", b:"Reconnaissance → scanning/enumeration → gaining access (exploitation) → maintaining access/pivoting → covering tracks (in scope-permitting tests) → reporting."},
  {d:6, f:"Passive vs. Active Reconnaissance", b:"Passive: no target contact — OSINT, DNS records, job postings, certificate transparency. Active: touching the target — port scans, banner grabbing. Passive is undetectable."},
  {d:6, f:"Banner Grabbing", b:"Reading service version strings from open ports to map the attack surface (Netcat, Nmap). Countermeasure: suppress or falsify banners."},
  {d:6, f:"SOC Reports", b:"SOC 1: financial reporting controls. SOC 2: security/availability/confidentiality controls — restricted distribution. SOC 3: public summary. Type I: design at a point in time. Type II: operating effectiveness over 6-12 months (strongest)."},
  {d:6, f:"Audit Independence", b:"Auditors must be independent of what they audit. Internal audit reports to the board's audit committee, not to IT management. External audits provide third-party assurance."},
  {d:6, f:"Fuzzing", b:"Bombarding an application with malformed/random input to trigger crashes and memory errors. Mutation fuzzing alters valid samples; generation fuzzing builds input from protocol specs."},
  {d:6, f:"Misuse/Abuse Case Testing", b:"Testing how an ATTACKER would abuse features — the inverse of use case testing. Verifies the application resists hostile behavior, not just that features work."},
  {d:6, f:"Synthetic Transactions", b:"Scripted user journeys (e.g., login → search → checkout) run continuously from outside to verify availability, correctness, and performance before real users hit problems."},
  {d:6, f:"Regression Testing", b:"Re-running existing tests after changes/patches to confirm previously working functionality still works. Essential after emergency patches."},
  {d:6, f:"Code Coverage", b:"Percentage of code exercised by tests: statement, branch, condition, function coverage. High coverage ≠ correctness, but low coverage = untested code."},
  {d:6, f:"Interface Testing", b:"Testing boundaries between components: APIs, UIs, physical interfaces. Verifies contracts, error handling, and security at every integration point."},
  {d:6, f:"Log Review Essentials", b:"Centralize (SIEM), protect integrity (append-only, hashing), synchronize time (NTP), define retention, and actually review — logs nobody reads provide no detection."},
  {d:6, f:"SIEM", b:"Security Information and Event Management: aggregates and correlates logs across sources, alerts on patterns, supports investigations and compliance reporting."},
  {d:6, f:"Clipping Level", b:"Threshold below which events aren't flagged (e.g., alert after 5 failed logins, not 1). Filters noise while catching significant patterns."},
  {d:6, f:"Vulnerability Management Cycle", b:"Discover (scan) → prioritize (CVSS + asset criticality + exploitability) → remediate/mitigate → verify (rescan) → report. Continuous, not annual."},
  {d:6, f:"CVSS", b:"Common Vulnerability Scoring System: 0-10 severity from exploitability and impact metrics. 9.0+ critical. Context (exposure, asset value) must adjust raw scores."},
  {d:6, f:"False Positive vs. False Negative", b:"False positive: alert with no real issue — wastes effort, breeds alert fatigue. False negative: real issue missed — the dangerous one. Tuning trades between them."},
  {d:6, f:"Account Access Review", b:"Periodic recertification: managers confirm each user's entitlements are still required. Detects privilege creep, orphaned accounts, toxic combinations violating separation of duties."},
  {d:6, f:"Key Risk vs. Key Performance Indicators", b:"KPI: backward-looking performance measurement (patch time, incidents closed). KRI: forward-looking early warning that risk exposure is rising."},
  {d:6, f:"Attestation vs. Verification", b:"Attestation: management or third party asserts controls exist (SOC report). Verification/validation: direct testing proving controls actually work."},
  {d:6, f:"Breach and Attack Simulation (BAS)", b:"Automated tools continuously running known attack techniques (often MITRE ATT&CK-mapped) to validate that defenses detect and block them — between pen tests."},

  // Domain 7 — Security Operations (25)
  {d:7, f:"Incident Response Phases (CISSP)", b:"Preparation → Detection → Response (containment) → Mitigation (eradication) → Reporting → Recovery → Remediation (root cause) → Lessons Learned."},
  {d:7, f:"Order of Volatility", b:"Collect most volatile first: CPU registers/cache → RAM, network state, running processes → swap → disk → backups/archives → printed material."},
  {d:7, f:"Chain of Custody", b:"Documentation of who collected, handled, transferred, and stored evidence, when and how. Gaps let opposing counsel allege tampering — can render evidence inadmissible."},
  {d:7, f:"Forensic Imaging", b:"Bit-for-bit copy of media using a write blocker; hash original and copy (before and after) to prove integrity; analyze only the copy, never the original."},
  {d:7, f:"Full / Incremental / Differential Backups", b:"Full: everything. Incremental: changes since last backup of ANY type (fast backup, slow restore — need full + all incrementals). Differential: changes since last FULL (restore = full + latest differential)."},
  {d:7, f:"3-2-1 Backup Rule", b:"3 copies of data, on 2 different media types, 1 offsite. Modern addition: one copy immutable/offline for ransomware resistance."},
  {d:7, f:"RAID Levels", b:"RAID 0: striping, no redundancy. RAID 1: mirroring. RAID 5: striping + single parity (survives 1 disk). RAID 6: double parity (survives 2). RAID 10: mirror + stripe (performance + redundancy)."},
  {d:7, f:"Hot / Warm / Cold Sites", b:"Hot: full hardware + near-current data, recovery in minutes-hours, highest cost. Warm: hardware, data restored from backup, hours-days. Cold: space and power only, weeks. Cloud DR blurs tiers."},
  {d:7, f:"DR Test Types (increasing risk)", b:"Checklist review → tabletop/structured walkthrough → simulation → parallel test (recovery systems run alongside production) → full interruption (actual failover — most assurance, most risk)."},
  {d:7, f:"MTBF / MTTR", b:"MTBF: Mean Time Between Failures — expected reliability. MTTR: Mean Time To Repair — expected restoration time. Drive maintenance and redundancy planning."},
  {d:7, f:"Honeypot / Honeynet", b:"Decoy systems designed to attract attackers — early detection and intelligence. Must entice, not entrap. Darknets: monitored unused IP space where any traffic is suspicious."},
  {d:7, f:"Sandboxing (malware analysis)", b:"Detonating suspicious files in isolated instrumented environments to observe behavior (file writes, registry, C2 callbacks) without risk. Advanced malware detects sandboxes and stalls."},
  {d:7, f:"Threat Hunting", b:"Proactive, hypothesis-driven search for attackers already inside — assumes automated alerting missed them. Uses ATT&CK TTPs, anomalies, and IOCs rather than waiting for alarms."},
  {d:7, f:"Threat Intelligence & IOCs", b:"Intel: contextualized threat knowledge (actors, TTPs, campaigns) — strategic to tactical. IOCs: observable evidence of compromise (hashes, IPs, domains) fed into detection tools. Standards: STIX/TAXII."},
  {d:7, f:"SOAR", b:"Security Orchestration, Automation and Response: playbooks automate repetitive response tasks (enrichment, containment, notification) — faster response, less analyst fatigue."},
  {d:7, f:"EDR / XDR", b:"EDR: continuous endpoint telemetry, detection, and remote response (isolate host, kill process). XDR extends correlation across endpoint, network, identity, email, and cloud."},
  {d:7, f:"Application Allowlisting", b:"Only approved executables may run; everything else is blocked by default. Far stronger than denylisting (blocking known bad) — stops unknown malware."},
  {d:7, f:"Patch Management Process", b:"Inventory → monitor advisories → risk-prioritize → TEST in staging → phased deployment → verify → document exceptions with compensating controls."},
  {d:7, f:"Change Management", b:"Formal process: request → impact/risk analysis → approval (CAB) → scheduled implementation with rollback plan → review. Prevents outages and unauthorized changes; emergency changes get retroactive review."},
  {d:7, f:"Configuration Management", b:"Baseline approved configurations, control drift, detect unauthorized changes. CMDB tracks assets and relationships. Foundation for hardening (CIS Benchmarks)."},
  {d:7, f:"Egress Monitoring", b:"Inspecting OUTBOUND traffic for data exfiltration and C2 callbacks — DLP, TLS inspection, DNS monitoring. Attackers must eventually communicate out."},
  {d:7, f:"Dual Control vs. Split Knowledge", b:"Dual control: two people must act together (two keys). Split knowledge: each person holds only part of a secret (half a key each). Both prevent unilateral abuse."},
  {d:7, f:"eDiscovery & Legal Hold", b:"Legal hold suspends normal retention/deletion for potentially relevant data when litigation is anticipated. Spoliation (destroying held data) brings severe sanctions."},
  {d:7, f:"UPS vs. Generator", b:"UPS: instant battery power bridging seconds-minutes (ride-through and graceful shutdown). Generator: sustained power after a startup gap. Data centers need both, plus fuel contracts."},
  {d:7, f:"MTD Formula Relationship", b:"RTO + WRT (work recovery time to validate/resume business) must be ≤ MTD. If recovery can't fit inside MTD, redesign the strategy (better site tier, more redundancy)."},

  // Domain 8 — Software Development Security (25)
  {d:8, f:"Secure SDLC", b:"Integrate security into every phase: requirements (security requirements), design (threat modeling), build (secure coding, SAST), test (DAST, pen test), deploy (hardening), operate (patching, monitoring). 'Shift left' — earlier is cheaper."},
  {d:8, f:"Waterfall vs. Agile vs. DevSecOps", b:"Waterfall: sequential phases, late testing. Agile: iterative sprints, continuous feedback. DevSecOps: security automated INTO the CI/CD pipeline — everyone owns security."},
  {d:8, f:"Threat Modeling in Design", b:"Identify threats before code exists: decompose the app (DFDs, trust boundaries), enumerate threats (STRIDE), rank, and design mitigations. Cheapest point to fix flaws."},
  {d:8, f:"SQL Injection", b:"Malicious input executed as SQL. Defense: parameterized queries/prepared statements (primary), stored procedures, least-privilege DB accounts, input validation, WAF (secondary)."},
  {d:8, f:"XSS — Three Types", b:"Reflected: payload in the request, echoed back (needs phishing link). Stored: payload saved server-side, hits every visitor (worst). DOM-based: client-side script sinks. Defense: output encoding + input validation + CSP."},
  {d:8, f:"CSRF", b:"Tricks a logged-in browser into sending unwanted authenticated requests. Defense: anti-CSRF tokens per session/request, SameSite cookies, re-authentication for sensitive actions."},
  {d:8, f:"IDOR / BOLA", b:"Changing an ID in a request to access someone else's object (e.g., /account?id=124). Missing object-level authorization checks. #1 API vulnerability. Every request must verify ownership."},
  {d:8, f:"Buffer Overflow", b:"Writing past allocated memory to corrupt adjacent data or hijack execution. Defenses: bounds checking, memory-safe languages, ASLR, DEP/NX, stack canaries."},
  {d:8, f:"TOCTOU / Race Conditions", b:"State changes between a check and its use (time-of-check to time-of-use). Defense: atomic operations, locking, re-verify at time of use."},
  {d:8, f:"Input Validation", b:"Allowlist validation (accept known good) beats denylist (block known bad). Validate type, length, range, format — server-side always; client-side is UX only, trivially bypassed."},
  {d:8, f:"SAST vs. DAST vs. IAST vs. SCA", b:"SAST: scans source code (white box, early, finds code flaws). DAST: probes running app (black box, finds runtime issues). IAST: instrumented agents during testing. SCA: inventories third-party/open-source dependencies for known CVEs."},
  {d:8, f:"Software Supply Chain Security", b:"Attacks poison dependencies/build pipelines (SolarWinds, Log4j). Defenses: SBOM, SCA, signed artifacts, dependency pinning, secured build systems (SLSA)."},
  {d:8, f:"CI/CD Pipeline Security", b:"Least-privilege pipeline access, secrets in a vault (never in code), signed commits and artifacts, isolated build runners, security gates (SAST/SCA) that fail builds."},
  {d:8, f:"Code Signing", b:"Digitally signing executables/scripts proves publisher identity and integrity. Compromised signing keys are catastrophic — protect in HSMs."},
  {d:8, f:"Secrets Management", b:"No hardcoded credentials/API keys in source. Use vaults with rotation, short-lived credentials, audited access. Scan repos for leaked secrets."},
  {d:8, f:"OWASP Top 10 (themes)", b:"Broken access control, cryptographic failures, injection, insecure design, misconfiguration, vulnerable components, auth failures, integrity failures, logging failures, SSRF. Know categories, not just the list."},
  {d:8, f:"SSRF", b:"Server-Side Request Forgery: tricking a server into making requests to internal resources (cloud metadata endpoints, internal APIs). Defense: allowlist outbound destinations, block link-local addresses, network segmentation."},
  {d:8, f:"Polyinstantiation", b:"Multiple rows with the same key at different classification levels in an MLS database — prevents low-clearance users from inferring classified data via constraint conflicts."},
  {d:8, f:"Inference vs. Aggregation", b:"Aggregation: combining individually harmless data into sensitive knowledge. Inference: DEDUCING restricted info from authorized queries. Defenses: polyinstantiation, query restrictions, cell suppression."},
  {d:8, f:"ACID Properties", b:"Atomicity (all or nothing), Consistency (valid state to valid state), Isolation (concurrent transactions don't interfere), Durability (committed = permanent)."},
  {d:8, f:"Memory-Safe Languages", b:"Rust, Go, Java, C#, Python enforce bounds and memory management — eliminating most buffer overflow/use-after-free classes that plague C/C++."},
  {d:8, f:"CMM Levels", b:"1 Initial (chaotic) → 2 Managed/Repeatable → 3 Defined (documented org-wide) → 4 Quantitatively Managed (measured) → 5 Optimizing (continuous improvement)."},
  {d:8, f:"Cohesion and Coupling", b:"HIGH cohesion (module does one thing well) + LOW coupling (minimal dependencies between modules) = maintainable, secure design."},
  {d:8, f:"API Security Essentials", b:"Strong authentication (OAuth/OIDC), object-level authorization on every request, rate limiting, input validation, no sensitive data in URLs, versioning and inventory (no shadow APIs)."},
  {d:8, f:"Fail Securely (software)", b:"On error, deny access and fail to a safe state — never expose stack traces, debug data, or default-allow behavior. Error messages generic to users, detailed only in secure logs."}
];
