// CISSP Prep — Question Bank
// Format: d = domain (1-8), q = question, c = choices, a = index of correct answer, e = explanation
const DOMAINS = {
  1: "Security & Risk Management",
  2: "Asset Security",
  3: "Security Architecture & Engineering",
  4: "Communication & Network Security",
  5: "Identity & Access Management",
  6: "Security Assessment & Testing",
  7: "Security Operations",
  8: "Software Development Security"
};

const ENTRY_QUESTIONS = [
  // Domain 1 — Security & Risk Management (8)
  {d:1, q:"Which element of the CIA triad ensures that authorized users can access systems and data when needed?", c:["Confidentiality","Integrity","Availability","Authenticity"], a:2, e:"Availability ensures timely, reliable access to data and resources for authorized users."},
  {d:1, q:"Risk is BEST defined as:", c:["Any weakness in a system","The likelihood of a threat exploiting a vulnerability and the resulting impact","Any potential danger to an organization","The absence of security controls"], a:1, e:"Risk = threat × vulnerability × impact. It combines the likelihood of a threat exploiting a weakness with the resulting harm."},
  {d:1, q:"A written high-level statement from senior management describing the organization's security goals is a:", c:["Guideline","Procedure","Standard","Policy"], a:3, e:"Policies are mandatory high-level management statements. Standards are mandatory specifics; guidelines are recommendations; procedures are step-by-step instructions."},
  {d:1, q:"Which formula correctly calculates Annualized Loss Expectancy (ALE)?", c:["ALE = SLE × ARO","ALE = AV × ARO","ALE = SLE × EF","ALE = AV × EF × RTO"], a:0, e:"ALE = Single Loss Expectancy (SLE) × Annualized Rate of Occurrence (ARO). SLE itself = Asset Value × Exposure Factor."},
  {d:1, q:"Granting users only the access required to perform their job duties is the principle of:", c:["Separation of duties","Least privilege","Need to know","Job rotation"], a:1, e:"Least privilege limits users to the minimum access rights necessary for their role. Need to know is related but applies specifically to access to information."},
  {d:1, q:"Who is ULTIMATELY responsible for security within an organization?", c:["The CISO","The security team","Senior management","Each individual employee"], a:2, e:"Senior management is ultimately accountable for security. The CISO and security team implement and manage it on their behalf."},
  {d:1, q:"Practicing 'due care' means an organization:", c:["Investigates and understands its risks","Takes reasonable actions to protect its assets","Purchases cybersecurity insurance","Documents all security incidents"], a:1, e:"Due care is doing what a reasonable organization would do to protect assets (acting). Due diligence is the research and investigation that informs those actions."},
  {d:1, q:"GDPR is an example of which type of requirement?", c:["Contractual","Regulatory","Industry standard","Voluntary framework"], a:1, e:"GDPR is a legal/regulatory requirement imposed by the European Union, carrying legal penalties for non-compliance."},

  // Domain 2 — Asset Security (5)
  {d:2, q:"Who is responsible for assigning the classification level to data?", c:["Data custodian","Data owner","Data processor","System administrator"], a:1, e:"The data owner (typically a business manager) classifies data. Custodians implement day-to-day protection such as backups."},
  {d:2, q:"The PRIMARY purpose of data classification is to:", c:["Satisfy audit requirements","Determine the level of protection data requires","Organize files for easier searching","Reduce storage costs"], a:1, e:"Classification ensures data receives protection commensurate with its value and sensitivity."},
  {d:2, q:"Data remanence refers to:", c:["Data kept beyond its retention period","Residual data remaining on media after deletion","Duplicate copies of data","Data stored in foreign countries"], a:1, e:"Data remanence is the residual representation of data that remains on media even after attempts to erase it."},
  {d:2, q:"Which role performs day-to-day tasks such as backups and applying security controls to data?", c:["Data owner","Data subject","Data custodian","Data controller"], a:2, e:"The data custodian handles technical, day-to-day care of data on behalf of the data owner."},
  {d:2, q:"Which of the following is the BEST way to ensure data on a magnetic hard drive cannot be recovered before disposal?", c:["Deleting all files","Formatting the drive","Physical destruction","Emptying the recycle bin"], a:2, e:"Physical destruction (shredding, incineration) is the most reliable sanitization method. Deleting and formatting leave recoverable data."},

  // Domain 3 — Security Architecture & Engineering (7)
  {d:3, q:"Which type of cryptography uses the SAME key to encrypt and decrypt?", c:["Asymmetric","Symmetric","Hashing","Elliptic curve"], a:1, e:"Symmetric cryptography (e.g., AES) uses one shared secret key. Asymmetric uses a public/private key pair."},
  {d:3, q:"Hashing is PRIMARILY used to provide:", c:["Confidentiality","Availability","Integrity","Authorization"], a:2, e:"A hash produces a fixed-length digest; any change to the data changes the digest, revealing tampering — that is integrity."},
  {d:3, q:"Using multiple layers of different security controls so that no single failure exposes the organization is called:", c:["Security through obscurity","Defense in depth","Zero trust","Fail secure"], a:1, e:"Defense in depth layers administrative, technical, and physical controls so one failed control does not cause total compromise."},
  {d:3, q:"The Bell-LaPadula model is focused on:", c:["Integrity","Availability","Confidentiality","Non-repudiation"], a:2, e:"Bell-LaPadula enforces confidentiality: 'no read up, no write down.' Biba is its integrity-focused counterpart."},
  {d:3, q:"A Trusted Platform Module (TPM) is:", c:["A software firewall","A hardware chip that stores cryptographic keys","A biometric scanner","A network intrusion sensor"], a:1, e:"A TPM is a dedicated hardware chip on the motherboard that securely stores keys, supporting features like full-disk encryption."},
  {d:3, q:"In an emergency, a data center door that automatically UNLOCKS when power fails is configured as:", c:["Fail secure","Fail safe","Fail closed","Fail hard"], a:1, e:"Fail safe (fail open) prioritizes human life — people can exit during a power failure. Fail secure keeps the door locked."},
  {d:3, q:"Encrypting a laptop's hard drive protects data in which state?", c:["Data in transit","Data in use","Data at rest","Data in process"], a:2, e:"Full-disk encryption protects stored data — data at rest. TLS protects data in transit."},

  // Domain 4 — Communication & Network Security (7)
  {d:4, q:"At which OSI layer does the IP protocol operate?", c:["Layer 2 — Data Link","Layer 3 — Network","Layer 4 — Transport","Layer 5 — Session"], a:1, e:"IP handles logical addressing and routing at Layer 3, the Network layer."},
  {d:4, q:"TCP port 443 is used by default for:", c:["HTTP","FTP","HTTPS","SSH"], a:2, e:"HTTPS (HTTP over TLS) uses port 443. HTTP uses 80, FTP 20/21, SSH 22."},
  {d:4, q:"The PRIMARY function of a firewall is to:", c:["Encrypt network traffic","Filter traffic between networks based on rules","Detect malware on endpoints","Assign IP addresses"], a:1, e:"A firewall enforces an access control policy by permitting or denying traffic between network zones."},
  {d:4, q:"A VPN is used PRIMARILY to:", c:["Speed up network connections","Create an encrypted tunnel over an untrusted network","Block malicious websites","Load-balance traffic"], a:1, e:"A VPN provides a secure, encrypted tunnel across untrusted networks such as the Internet."},
  {d:4, q:"Which transport protocol is connection-oriented and guarantees delivery?", c:["UDP","ICMP","TCP","ARP"], a:2, e:"TCP establishes a connection (three-way handshake) and provides reliable, ordered delivery. UDP is connectionless best-effort."},
  {d:4, q:"A network segment that hosts public-facing servers while isolating them from the internal network is a:", c:["VLAN trunk","DMZ (screened subnet)","Honeynet","Intranet"], a:1, e:"A DMZ/screened subnet exposes public services (web, mail) while shielding the internal LAN if those servers are compromised."},
  {d:4, q:"Which wireless security protocol provides the STRONGEST protection?", c:["WEP","WPA","WPA2","WPA3"], a:3, e:"WPA3 is the current strongest Wi-Fi standard, adding SAE handshakes that resist offline dictionary attacks. WEP is trivially broken."},

  // Domain 5 — Identity & Access Management (7)
  {d:5, q:"Providing a username is an example of ________, while providing the password is ________.", c:["authentication; authorization","identification; authentication","authorization; accounting","identification; authorization"], a:1, e:"Identification is claiming an identity (username); authentication is proving it (password); authorization determines what you may access."},
  {d:5, q:"A smart card combined with a PIN is an example of:", c:["Two factors: something you have and something you know","Two factors: something you are and something you know","Single-factor authentication","Something you have and something you are"], a:0, e:"The card is a possession factor (have) and the PIN is a knowledge factor (know) — true multifactor authentication."},
  {d:5, q:"Access permissions assigned based on a user's job function are an example of:", c:["Discretionary access control (DAC)","Mandatory access control (MAC)","Role-based access control (RBAC)","Rule-based access control"], a:2, e:"RBAC assigns permissions to roles (e.g., 'Accountant'), and users inherit permissions through role membership."},
  {d:5, q:"The MAIN risk introduced by single sign-on (SSO) is:", c:["Users must remember more passwords","A compromised credential grants access to many systems","It cannot work with MFA","Slower login times"], a:1, e:"SSO is convenient but a single compromised credential unlocks every connected system — the 'keys to the kingdom' problem. Pair SSO with MFA."},
  {d:5, q:"In biometrics, a false acceptance occurs when:", c:["A legitimate user is rejected","An imposter is granted access","The scanner fails to read","Enrollment fails"], a:1, e:"False acceptance (Type II error) admits an unauthorized person — generally the more dangerous error. False rejection (Type I) blocks a legitimate user."},
  {d:5, q:"When an employee is terminated, their system access should be:", c:["Disabled within 30 days","Reviewed at the next quarterly audit","Revoked immediately","Transferred to their manager"], a:2, e:"Immediate deprovisioning prevents disgruntled ex-employees or attackers from using orphaned accounts."},
  {d:5, q:"Which of the following BEST describes 'something you are' authentication?", c:["A password","A hardware token","A fingerprint","A security question"], a:2, e:"Biometrics (fingerprint, iris, face) are inherence factors — something you are."},

  // Domain 6 — Security Assessment & Testing (6)
  {d:6, q:"The key difference between a vulnerability scan and a penetration test is that a penetration test:", c:["Is fully automated","Actively exploits weaknesses to demonstrate impact","Only reviews documentation","Is always performed internally"], a:1, e:"Vulnerability scans identify potential weaknesses; penetration tests attempt to exploit them to prove real-world impact."},
  {d:6, q:"Audit logs are MOST useful for:", c:["Preventing attacks in real time","Reconstructing events after an incident","Encrypting sensitive data","Blocking unauthorized users"], a:1, e:"Logs are detective controls — they provide accountability and enable reconstruction of what happened."},
  {d:6, q:"In a black-box penetration test, the tester is given:", c:["Full source code and network diagrams","Administrator credentials","No prior knowledge of the environment","Only the security policy"], a:2, e:"Black box simulates an outside attacker with zero internal knowledge. White box provides full knowledge; gray box is partial."},
  {d:6, q:"Reviewing application source code for flaws without executing the program is called:", c:["Dynamic analysis","Fuzz testing","Static analysis","Regression testing"], a:2, e:"Static analysis (SAST/code review) examines code at rest. Dynamic analysis tests the running application."},
  {d:6, q:"Sending simulated phishing emails to employees PRIMARILY tests:", c:["Email server configuration","The effectiveness of security awareness training","Firewall rules","Spam filter accuracy"], a:1, e:"Phishing simulations measure whether awareness training actually changed user behavior."},
  {d:6, q:"An independent examination of security controls against a defined standard is called a(n):", c:["Vulnerability scan","Audit","Tabletop exercise","Code review"], a:1, e:"An audit formally evaluates controls against criteria (e.g., ISO 27001, SOC 2) and is ideally performed by an independent party."},

  // Domain 7 — Security Operations (6)
  {d:7, q:"Which phase of incident response comes FIRST?", c:["Detection","Preparation","Containment","Recovery"], a:1, e:"Preparation (plans, training, tooling) precedes everything. The typical flow: Preparation → Detection → Response/Containment → Mitigation → Reporting → Recovery → Remediation → Lessons Learned."},
  {d:7, q:"A backup that copies only data changed since the LAST BACKUP OF ANY TYPE is a(n):", c:["Full backup","Differential backup","Incremental backup","Mirror backup"], a:2, e:"Incremental backs up changes since the last backup of any kind and resets the archive bit. Differential copies everything changed since the last FULL backup."},
  {d:7, q:"Requiring two people to complete a critical task, such as releasing a wire transfer, is an example of:", c:["Least privilege","Separation of duties","Job rotation","Mandatory vacation"], a:1, e:"Separation of duties splits critical functions so no single person can commit fraud alone. Two-person control is a form of it."},
  {d:7, q:"RAID 1 provides fault tolerance through:", c:["Striping","Parity","Mirroring","Compression"], a:2, e:"RAID 1 writes identical data to two drives (mirroring). RAID 0 stripes with no redundancy; RAID 5 stripes with parity."},
  {d:7, q:"Which disaster recovery site can take over operations FASTEST?", c:["Cold site","Warm site","Hot site","Reciprocal site"], a:2, e:"A hot site has hardware, connectivity, and near-current data ready — recovery in minutes to hours, at the highest cost."},
  {d:7, q:"Chain of custody documentation is maintained PRIMARILY to:", c:["Speed up incident recovery","Prove evidence was not altered or mishandled","Identify the attacker","Satisfy backup requirements"], a:1, e:"Chain of custody tracks who handled evidence, when, and how — preserving its integrity and admissibility in court."},

  // Domain 8 — Software Development Security (4)
  {d:8, q:"The BEST defense against SQL injection is:", c:["Encrypting the database","Parameterized queries (prepared statements)","Using a web application firewall only","Hiding error messages"], a:1, e:"Parameterized queries separate code from data so user input can never be executed as SQL. WAFs help but are a compensating layer."},
  {d:8, q:"When should security be introduced into the software development lifecycle?", c:["During testing","After deployment","At the requirements/design phase","Only when handling payment data"], a:2, e:"Security is cheapest and most effective when built in from the earliest phases — 'shift left.'"},
  {d:8, q:"Cross-site scripting (XSS) allows an attacker to:", c:["Execute malicious scripts in a victim's browser","Overflow a memory buffer","Intercept network traffic","Escalate OS privileges"], a:0, e:"XSS injects attacker-controlled script into pages viewed by other users, running in their browser context. Output encoding and input validation prevent it."},
  {d:8, q:"A buffer overflow attack is BEST prevented by:", c:["Strong passwords","Input validation and bounds checking","Disk encryption","Network segmentation"], a:1, e:"Bounds checking and input validation (plus memory-safe languages, ASLR, DEP) prevent writing past allocated memory."}
];

const INTERMEDIATE_QUESTIONS = [
  // Domain 1 — Security & Risk Management (15)
  {d:1, q:"A server worth $200,000 has an exposure factor of 25% for a given threat, which is expected to occur once every 4 years. What is the ALE?", c:["$50,000","$12,500","$25,000","$200,000"], a:1, e:"SLE = $200,000 × 0.25 = $50,000. ARO = 1/4 = 0.25. ALE = $50,000 × 0.25 = $12,500."},
  {d:1, q:"An organization purchases cyber insurance to address a risk it cannot economically mitigate. This is risk:", c:["Acceptance","Avoidance","Transference","Mitigation"], a:2, e:"Insurance shifts the financial impact to a third party — risk transference (sharing). The risk itself still exists."},
  {d:1, q:"After controls are applied, the risk that remains is called:", c:["Inherent risk","Total risk","Residual risk","Secondary risk"], a:2, e:"Residual risk is what remains after mitigation. It must be formally accepted by senior management, not the security team."},
  {d:1, q:"A company researches a cloud vendor's security posture, certifications, and financials before signing a contract. This is an example of:", c:["Due care","Due diligence","Risk avoidance","Compliance testing"], a:1, e:"Due diligence is the investigation/research that informs decisions. Due care would be acting on it (e.g., adding contract controls)."},
  {d:1, q:"In a Business Impact Analysis, the metric that defines the MAXIMUM tolerable amount of data loss measured in time is:", c:["RTO","MTD","RPO","MTBF"], a:2, e:"Recovery Point Objective (RPO) defines how much data (in time) can be lost — it drives backup frequency. RTO is time to restore service; MTD is maximum tolerable downtime."},
  {d:1, q:"In the STRIDE threat model, an attacker using a forged authentication token falls under:", c:["Tampering","Spoofing","Repudiation","Elevation of privilege"], a:1, e:"Spoofing is impersonating a user, system, or process. STRIDE: Spoofing, Tampering, Repudiation, Information disclosure, Denial of service, Elevation of privilege."},
  {d:1, q:"A legacy system cannot be patched, so the organization isolates it on a separate VLAN with strict firewall rules. The firewall rules are a(n):", c:["Corrective control","Compensating control","Deterrent control","Recovery control"], a:1, e:"A compensating control provides alternative protection when the primary control (patching) is not feasible."},
  {d:1, q:"Security awareness training is what type of control?", c:["Technical / preventive","Administrative / preventive","Physical / deterrent","Technical / detective"], a:1, e:"Training is an administrative (management) control intended to prevent incidents by changing behavior."},
  {d:1, q:"Under GDPR, the organization that determines the purposes and means of processing personal data is the:", c:["Data processor","Data controller","Data custodian","Supervisory authority"], a:1, e:"The controller decides why and how data is processed; the processor acts on the controller's instructions."},
  {d:1, q:"Which intellectual property protection lasts indefinitely, provided the information is kept confidential?", c:["Patent","Copyright","Trademark","Trade secret"], a:3, e:"Trade secrets (e.g., a formula) are protected as long as secrecy is maintained. Patents expire (~20 years) and require public disclosure."},
  {d:1, q:"According to the (ISC)² Code of Ethics, a CISSP's FIRST obligation is to:", c:["Advance the profession","Protect society, the common good, and the infrastructure","Act honorably and legally","Provide diligent service to principals"], a:1, e:"The canons are ordered: 1) Protect society; 2) Act honorably, honestly, justly, responsibly, legally; 3) Provide diligent and competent service; 4) Advance and protect the profession."},
  {d:1, q:"In the NIST Risk Management Framework, the FIRST step is to:", c:["Select controls","Categorize the system","Assess controls","Authorize the system"], a:1, e:"RMF: Prepare → Categorize → Select → Implement → Assess → Authorize → Monitor."},
  {d:1, q:"A Key Risk Indicator (KRI) is BEST described as a metric that:", c:["Measures achievement of business goals","Provides early warning that risk exposure is increasing","Counts security incidents after they occur","Tracks project milestones"], a:1, e:"KRIs are forward-looking signals of rising risk, enabling proactive response. KPIs measure performance against goals."},
  {d:1, q:"The MOST effective way to manage risk from a third-party software supplier is to:", c:["Require the vendor to carry insurance","Perform security assessments and include security requirements in the contract","Only buy from large vendors","Scan the software after deployment"], a:1, e:"Supply chain risk management combines vendor assessment with contractual security obligations (right to audit, SLAs, notification requirements)."},
  {d:1, q:"Threat modeling should be performed:", c:["Only after a breach","Once, at system deployment","Early in design and repeated as the system changes","Annually by external auditors only"], a:2, e:"Threat modeling is most valuable in design ('shift left') and must be revisited as architecture and threats evolve."},

  // Domain 2 — Asset Security (10)
  {d:2, q:"Per NIST SP 800-88, which sanitization method removes data with the assurance it cannot be recovered by laboratory techniques, while keeping media reusable?", c:["Clear","Purge","Destroy","Erase"], a:1, e:"Purge (e.g., degaussing, crypto erase, secure overwrite) defeats laboratory recovery while media may remain usable. Clear defeats simple recovery; Destroy renders media unusable."},
  {d:2, q:"Crypto-shredding is the practice of:", c:["Physically shredding encrypted drives","Destroying the encryption keys so encrypted data becomes unrecoverable","Encrypting data multiple times","Splitting keys among custodians"], a:1, e:"If data is strongly encrypted, destroying all copies of the key renders the data permanently inaccessible — useful for cloud storage you cannot physically destroy."},
  {d:2, q:"An organization adapts a control baseline by removing controls that do not apply to its environment. This is called:", c:["Scoping","Tailoring","Categorization","Accreditation"], a:0, e:"Scoping removes inapplicable controls; tailoring further adjusts/parameterizes remaining controls (the terms are related — scoping selects, tailoring customizes)."},
  {d:2, q:"Digital Rights Management (DRM/IRM) PRIMARILY protects data by:", c:["Encrypting network links","Enforcing usage restrictions that travel with the file","Blocking USB ports","Watermarking printed documents"], a:1, e:"IRM/DRM embeds persistent controls (no print, no forward, expiry) that follow the document wherever it goes."},
  {d:2, q:"Which technology allows computation on data WHILE it remains encrypted?", c:["TLS 1.3","Homomorphic encryption","Tokenization","Perfect forward secrecy"], a:1, e:"Homomorphic encryption permits processing of ciphertext — protecting data in use. Secure enclaves are a hardware alternative."},
  {d:2, q:"A law requiring citizens' personal data to be stored on servers physically located within the country is an example of:", c:["Data remanence","Data sovereignty / localization","Safe harbor","Data portability"], a:1, e:"Data localization/sovereignty laws tie data storage and legal jurisdiction to geographic borders — a key cloud architecture consideration."},
  {d:2, q:"Why is an accurate asset inventory considered a PREREQUISITE for security management?", c:["It reduces licensing costs","You cannot protect or classify assets you do not know exist","Auditors require it","It speeds up procurement"], a:1, e:"Classification, patching, monitoring, and risk assessment all depend on knowing what assets exist and who owns them."},
  {d:2, q:"Replacing names with a reference number, while keeping a separate lookup table, is:", c:["Anonymization","Pseudonymization","Aggregation","Masking"], a:1, e:"Pseudonymization is reversible via the lookup table and still regulated under GDPR. True anonymization is irreversible."},
  {d:2, q:"Which factor should have the GREATEST influence on data retention periods?", c:["Storage cost","Legal and regulatory requirements","Backup software capabilities","Employee preference"], a:1, e:"Retention schedules are driven primarily by legal/regulatory/contractual obligations; keeping data longer than required increases liability."},
  {d:2, q:"An SSD is being decommissioned. Which sanitization method is LEAST reliable for it?", c:["Cryptographic erase","Vendor secure-erase command","Multi-pass overwriting","Physical destruction"], a:2, e:"Wear-leveling on SSDs means overwriting may miss remapped cells. Crypto erase, vendor sanitize commands, or destruction are preferred."},

  // Domain 3 — Security Architecture & Engineering (13)
  {d:3, q:"The Biba model's 'simple integrity axiom' states that a subject cannot:", c:["Write to a higher integrity level","Read from a lower integrity level","Read from a higher integrity level","Write to the same integrity level"], a:1, e:"Biba: simple integrity = no read down; star (*) integrity = no write up. It prevents corruption from less-trusted sources."},
  {d:3, q:"Which security model enforces integrity through well-formed transactions and separation of duties, using access triples?", c:["Bell-LaPadula","Biba","Clark-Wilson","Graham-Denning"], a:2, e:"Clark-Wilson uses subject–program–object triples: users modify data only through trusted programs, enforcing integrity commercially."},
  {d:3, q:"The Brewer-Nash model is designed PRIMARILY to prevent:", c:["Privilege escalation","Conflicts of interest through dynamic access restrictions","Covert channels","Inference attacks"], a:1, e:"Brewer-Nash ('Chinese Wall') dynamically blocks access to competitors' data once you access one client's data — built for consultancies."},
  {d:3, q:"AES uses a fixed block size of:", c:["64 bits","128 bits","256 bits","Variable, matching the key size"], a:1, e:"AES always uses 128-bit blocks; only the key size varies (128, 192, or 256 bits)."},
  {d:3, q:"The Diffie-Hellman algorithm is used PRIMARILY for:", c:["Bulk data encryption","Digital signatures","Secure key agreement over an insecure channel","Hashing passwords"], a:2, e:"DH lets two parties derive a shared secret over a public channel. It provides no authentication by itself, so it is paired with signatures/certificates."},
  {d:3, q:"A digital signature provides all of the following EXCEPT:", c:["Integrity","Authenticity","Non-repudiation","Confidentiality"], a:3, e:"Signatures hash the message and encrypt the digest with the sender's private key — proving origin and integrity, but the message itself is not encrypted."},
  {d:3, q:"Compared with a CRL, OCSP's PRIMARY advantage is:", c:["It works offline","Real-time certificate status checks without downloading the full revocation list","Stronger encryption","It eliminates the need for a CA"], a:1, e:"OCSP queries the status of a single certificate in real time; CRLs are bulky lists that clients must download and may be stale."},
  {d:3, q:"An attacker deduces an encryption key by measuring the power consumption of a smart card during operations. This is a:", c:["Brute-force attack","Side-channel attack","Chosen-plaintext attack","Meet-in-the-middle attack"], a:1, e:"Side-channel attacks exploit physical emanations (power, timing, EM, sound) rather than weaknesses in the algorithm itself."},
  {d:3, q:"Under the Common Criteria, the product or system being evaluated is called the:", c:["Protection Profile","Security Target","Target of Evaluation","Evaluation Assurance Level"], a:2, e:"The TOE is the evaluated product. The Security Target describes its claims; a Protection Profile states customer requirements; EAL1-7 rates evaluation depth."},
  {d:3, q:"A process signals sensitive information to another process by modulating its CPU utilization. This is an example of a:", c:["Race condition","Covert timing channel","Buffer overflow","Trapdoor"], a:1, e:"Covert channels leak data via mechanisms not intended for communication — timing channels modulate system behavior; storage channels use shared storage."},
  {d:3, q:"Which fire suppression system is MOST appropriate for an occupied data center?", c:["Wet pipe sprinklers","Clean agent (e.g., FM-200/inert gas)","Carbon dioxide flooding","Dry powder extinguishers"], a:1, e:"Clean agents suppress fire without damaging electronics and are safe for occupied spaces. CO2 displaces oxygen and endangers people."},
  {d:3, q:"Designing a facility with natural surveillance, territorial reinforcement, and access control landscaping reflects:", c:["Defense in depth","CPTED","Zero trust architecture","Layered fencing standards"], a:1, e:"Crime Prevention Through Environmental Design uses the physical environment (sight lines, lighting, landscaping) to deter crime."},
  {d:3, q:"Adding a unique random salt to each password before hashing PRIMARILY defends against:", c:["Brute-force of a single account","Rainbow table and precomputation attacks","Keyloggers","Phishing"], a:1, e:"Salts make each hash unique, so precomputed tables are useless and identical passwords produce different hashes."},

  // Domain 4 — Communication & Network Security (13)
  {d:4, q:"Within IPsec, which protocol provides confidentiality through encryption?", c:["AH","ESP","IKE","GRE"], a:1, e:"Encapsulating Security Payload (ESP) encrypts. Authentication Header (AH) provides only integrity/authentication. IKE negotiates keys."},
  {d:4, q:"During a TLS handshake, asymmetric cryptography is used PRIMARILY to:", c:["Encrypt all application data","Securely establish a symmetric session key","Compress the data stream","Authenticate the client's IP address"], a:1, e:"Asymmetric crypto authenticates the server and establishes a shared symmetric key; the fast symmetric cipher then encrypts the session."},
  {d:4, q:"The BEST defense against VLAN hopping via switch spoofing is to:", c:["Enable DTP on all ports","Disable auto-trunking and set access ports statically","Use larger VLAN IDs","Enable port mirroring"], a:1, e:"Disabling Dynamic Trunking Protocol negotiation and hard-coding access ports prevents an attacker's device from negotiating a trunk."},
  {d:4, q:"DNSSEC protects against DNS cache poisoning by providing:", c:["Encryption of DNS queries","Origin authentication and integrity of DNS responses","Anonymity for resolvers","Faster lookups"], a:1, e:"DNSSEC digitally signs DNS records so resolvers can verify authenticity and integrity. It does NOT encrypt queries (DoH/DoT do that)."},
  {d:4, q:"A SYN flood attack exploits:", c:["The TCP three-way handshake by never completing it","DNS recursion","ICMP redirect messages","ARP broadcast behavior"], a:0, e:"The attacker sends many SYNs and ignores SYN-ACKs, exhausting the server's half-open connection table. SYN cookies mitigate this."},
  {d:4, q:"In 802.1X, the network switch or wireless access point acts as the:", c:["Supplicant","Authenticator","Authentication server","Registrar"], a:1, e:"The client device is the supplicant, the switch/AP is the authenticator, and RADIUS is typically the authentication server."},
  {d:4, q:"Dynamic ARP Inspection (DAI) defends PRIMARILY against:", c:["SYN floods","On-path (man-in-the-middle) attacks via ARP poisoning","DNS tunneling","MAC flooding"], a:1, e:"DAI validates ARP packets against trusted DHCP snooping bindings, blocking gratuitous ARP replies used to intercept traffic."},
  {d:4, q:"Microsegmentation in a zero trust architecture means:", c:["Placing all servers in one protected zone","Applying granular per-workload policies so lateral movement is restricted","Using smaller subnet masks","Segmenting only the DMZ"], a:1, e:"Zero trust assumes breach: every workload-to-workload flow is authenticated and authorized, limiting lateral movement."},
  {d:4, q:"In software-defined networking, the controller resides in the:", c:["Data plane","Control plane","Management VLAN","Forwarding ASIC"], a:1, e:"SDN separates the control plane (routing decisions, centralized controller) from the data plane (packet forwarding on devices)."},
  {d:4, q:"Which statement about IPv6 is TRUE?", c:["It uses 64-bit addresses","IPsec support is built into the protocol suite","It requires NAT for Internet access","It is backward compatible with IPv4 headers"], a:1, e:"IPv6 uses 128-bit addresses and integrates IPsec support natively. Its vast address space removes the need for NAT."},
  {d:4, q:"A firewall that tracks the state of connections and allows return traffic automatically is a:", c:["Packet-filtering firewall","Circuit-level proxy","Stateful inspection firewall","Application-layer gateway only"], a:2, e:"Stateful firewalls maintain a connection table and permit replies to established sessions without explicit inbound rules."},
  {d:4, q:"Bluesnarfing is BEST described as:", c:["Sending unsolicited messages over Bluetooth","Unauthorized access and data theft from a Bluetooth device","Jamming Bluetooth frequencies","Cloning a Bluetooth headset"], a:1, e:"Bluesnarfing steals data (contacts, messages) via Bluetooth. Bluejacking merely sends unsolicited messages — annoying but not theft."},
  {d:4, q:"Converged protocols such as FCoE and iSCSI introduce risk PRIMARILY because:", c:["They are always unencrypted","Storage traffic traverses shared Ethernet networks, expanding the attack surface","They require public IP addresses","They cannot be segmented"], a:1, e:"Running storage over general-purpose IP/Ethernet exposes SAN traffic to network attacks unless isolated (dedicated VLANs/VSANs) and secured."},

  // Domain 5 — Identity & Access Management (13)
  {d:5, q:"In Kerberos, the Ticket Granting Ticket (TGT) is issued by the:", c:["Service server","Authentication Server within the KDC","Client workstation","Certificate authority"], a:1, e:"The KDC's Authentication Server issues the TGT after initial authentication; the Ticket Granting Service then issues service tickets."},
  {d:5, q:"Kerberos authentication fails across the domain. Which infrastructure issue is the MOST likely cause?", c:["Expired TLS certificates","Clock skew between systems exceeding tolerance","DNS zone transfer failure","DHCP scope exhaustion"], a:1, e:"Kerberos tickets are timestamped to prevent replay; clock skew beyond ~5 minutes causes authentication failures."},
  {d:5, q:"In a SAML federation, the organization that authenticates the user and issues assertions is the:", c:["Service provider","Identity provider","Relying party","Certificate authority"], a:1, e:"The IdP authenticates users and issues signed assertions; the SP (relying party) consumes them to grant access."},
  {d:5, q:"The key difference between OAuth 2.0 and OpenID Connect is:", c:["OAuth handles authentication; OIDC handles authorization","OAuth handles authorization delegation; OIDC adds an authentication layer on top","They are identical protocols","OIDC replaced SAML entirely"], a:1, e:"OAuth 2.0 delegates authorization (access to resources). OIDC extends it with ID tokens to prove who the user is (authentication)."},
  {d:5, q:"Access decisions based on user department, device health, time of day, and data sensitivity describe:", c:["RBAC","ABAC","DAC","MAC"], a:1, e:"Attribute-Based Access Control evaluates attributes of subject, object, action, and environment — enabling fine-grained, contextual policies."},
  {d:5, q:"In Mandatory Access Control, access decisions are made by:", c:["The resource owner","The system, comparing subject clearance to object labels","Department managers","Each application independently"], a:1, e:"MAC is enforced by the OS using security labels and clearances; owners cannot override it (unlike DAC)."},
  {d:5, q:"An employee who has changed roles three times still holds permissions from every previous role. The BEST remediation is:", c:["Implement SSO","Conduct periodic access reviews and recertification","Increase password complexity","Enable account lockout"], a:1, e:"Privilege creep is corrected by regular entitlement reviews where managers recertify or revoke access — ideally automated through IGA tooling."},
  {d:5, q:"When comparing biometric systems, the BEST single metric to evaluate overall accuracy is the:", c:["False acceptance rate","False rejection rate","Crossover error rate (CER)","Enrollment time"], a:2, e:"CER (where FAR = FRR) allows apples-to-apples comparison; lower CER = more accurate system."},
  {d:5, q:"Just-in-time (JIT) privileged access management PRIMARILY reduces risk by:", c:["Eliminating passwords","Granting admin rights only for the duration of a task, then revoking them","Requiring longer passwords for admins","Logging all admin activity"], a:1, e:"JIT PAM eliminates standing privileges — accounts hold elevated rights only during an approved window, shrinking the attack surface."},
  {d:5, q:"A firewall permitting traffic based on a configured ACL is an example of which access control type?", c:["Role-based","Rule-based","Discretionary","Attribute-based"], a:1, e:"Rule-based access control applies global rules (like firewall ACLs) to all subjects uniformly, regardless of identity."},
  {d:5, q:"Verifying a new employee's passport and background before creating their account is part of:", c:["Authentication","Identity proofing","Authorization","Federation"], a:1, e:"Identity proofing establishes that a real person is who they claim to be BEFORE credentials are issued (registration phase)."},
  {d:5, q:"Which session management practice BEST limits the impact of a stolen session token?", c:["Storing tokens in URL parameters","Short token lifetimes with re-authentication for sensitive actions","Using the same token across applications","Disabling logout functions"], a:1, e:"Short-lived tokens, rotation, and step-up authentication reduce the window an attacker can use a hijacked session."},
  {d:5, q:"An attacker who obtains a domain controller's Kerberos service account hash and forges TGTs is performing a:", c:["Pass-the-hash attack","Golden ticket attack","Kerberoasting attack","Silver ticket attack"], a:1, e:"With the KRBTGT account hash, attackers can forge Ticket Granting Tickets for any user — a 'golden ticket.' Kerberoasting cracks service account tickets offline."},

  // Domain 6 — Security Assessment & Testing (12)
  {d:6, q:"Place these penetration test phases in order: (1) exploitation, (2) reconnaissance, (3) reporting, (4) scanning/enumeration.", c:["2, 4, 1, 3","4, 2, 1, 3","2, 1, 4, 3","4, 1, 2, 3"], a:0, e:"Recon → scanning/enumeration → exploitation (and post-exploitation) → reporting."},
  {d:6, q:"The PRIMARY purpose of a rules of engagement document for a penetration test is to:", c:["List vulnerabilities to find","Define scope, authorized targets, methods, and timing to keep testing legal and safe","Guarantee no outages","Set the tester's fee"], a:1, e:"RoE provides written authorization and boundaries — without it, testing may be illegal and operationally dangerous."},
  {d:6, q:"Scripted transactions that continuously test a website's checkout flow from external locations are called:", c:["Fuzzing","Synthetic transactions","Regression tests","Use case testing"], a:1, e:"Synthetic transaction monitoring proactively verifies availability and performance of critical user journeys before real users are affected."},
  {d:6, q:"Submitting massive volumes of malformed, random input to an application to find crashes is:", c:["Static analysis","Fuzz testing","Branch coverage testing","Mutation testing"], a:1, e:"Fuzzing discovers input-handling flaws (crashes, memory corruption) by bombarding interfaces with unexpected data."},
  {d:6, q:"Misuse case testing differs from use case testing because it:", c:["Tests only performance","Models how an ATTACKER would abuse functionality","Requires source code","Is always automated"], a:1, e:"Misuse/abuse cases flip requirements around: instead of intended behavior, they test hostile behavior the system must resist."},
  {d:6, q:"A SOC 2 Type II report differs from Type I in that Type II:", c:["Covers financial controls only","Assesses operating effectiveness of controls over a period of time","Is available to the general public","Is performed by the vendor itself"], a:1, e:"Type I evaluates control design at a point in time; Type II tests whether controls operated effectively over a period (typically 6-12 months)."},
  {d:6, q:"Which SOC report is intended for public distribution?", c:["SOC 1","SOC 2","SOC 3","SOC 2 Type II"], a:2, e:"SOC 3 is a general-use summary seal. SOC 1 (financial) and SOC 2 (security controls) are restricted-distribution reports."},
  {d:6, q:"To maintain independence, an internal audit function should report to:", c:["The IT director it audits","The audit committee of the board","The security operations manager","The CFO's accounting team"], a:1, e:"Reporting to the board's audit committee keeps auditors independent from the management they evaluate."},
  {d:6, q:"A vulnerability scanner flags a critical finding on a server, but the administrator believes it is wrong. The BEST next step is to:", c:["Ignore the finding","Manually verify the finding before remediation or dismissal","Immediately rebuild the server","Rerun the same scan"], a:1, e:"Findings must be validated — false positives waste effort, but wrongly dismissing a true positive is worse. Manual verification settles it."},
  {d:6, q:"Connecting to a service and reading the version string it returns is called:", c:["Fingerprint spoofing","Banner grabbing","Session hijacking","War dialing"], a:1, e:"Banner grabbing collects service/version info used to map attack surface — simple recon via tools like Netcat or Nmap."},
  {d:6, q:"After applying an emergency patch, which testing verifies that existing functionality still works?", c:["Fuzz testing","Regression testing","Static analysis","Interface testing"], a:1, e:"Regression testing re-runs existing test suites to confirm changes didn't break previously working functionality."},
  {d:6, q:"Reviewing accounts to confirm each active user still requires access is called:", c:["Penetration testing","Account access review / recertification","Log clipping","Key performance measurement"], a:1, e:"Periodic access recertification validates that entitlements remain appropriate — a core detective control against privilege creep."},

  // Domain 7 — Security Operations (13)
  {d:7, q:"During incident response, which phase immediately FOLLOWS containment (response)?", c:["Detection","Mitigation","Recovery","Lessons learned"], a:1, e:"CISSP flow: Preparation → Detection → Response (containment) → Mitigation (eradication) → Reporting → Recovery → Remediation → Lessons Learned."},
  {d:7, q:"When collecting forensic evidence, which should be captured FIRST?", c:["Hard disk image","RAM contents and running processes","Backup tapes","Printed documents"], a:1, e:"Order of volatility: capture the most volatile first — CPU/registers, RAM, network state — before powering down for disk imaging."},
  {d:7, q:"Which action would MOST likely make digital evidence inadmissible in court?", c:["Imaging the drive with a write blocker","Analyzing a copy rather than the original","Gaps in the chain of custody documentation","Hashing the image before and after analysis"], a:2, e:"Undocumented custody gaps let opposing counsel argue tampering. Write blockers, working from copies, and hashing all support admissibility."},
  {d:7, q:"A RAID 5 array with five disks can tolerate the failure of how many disks without data loss?", c:["Zero","One","Two","Three"], a:1, e:"RAID 5 uses single distributed parity — it survives exactly one disk failure. RAID 6 (double parity) survives two."},
  {d:7, q:"The 3-2-1 backup rule states:", c:["3 backups, 2 clouds, 1 tape","3 copies of data, on 2 different media types, with 1 copy offsite","3 daily, 2 weekly, 1 monthly backup","3 admins, 2 keys, 1 vault"], a:1, e:"3-2-1 ensures resilience: three total copies, two media types, one geographically separate — protecting against device failure and site disasters."},
  {d:7, q:"Which relationship between recovery metrics MUST hold true?", c:["MTD ≤ RTO","RTO ≤ MTD","RPO ≥ MTD","RTO = RPO"], a:1, e:"The Recovery Time Objective must fit within the Maximum Tolerable Downtime, or the business fails before recovery completes. (RTO + WRT ≤ MTD.)"},
  {d:7, q:"Which DR test provides the MOST assurance but carries the HIGHEST risk of business disruption?", c:["Tabletop exercise","Structured walkthrough","Parallel test","Full interruption test"], a:3, e:"A full interruption test actually fails over production — maximum realism, maximum risk. Parallel tests run recovery systems alongside production."},
  {d:7, q:"Egress monitoring with DLP is PRIMARILY designed to detect:", c:["Inbound malware","Sensitive data leaving the organization","Slow network links","Unauthorized wireless access points"], a:1, e:"Data Loss Prevention inspects outbound traffic, email, and endpoints for sensitive content (PII, IP) being exfiltrated."},
  {d:7, q:"Detonating a suspicious file in an isolated environment to observe its behavior is called:", c:["Fuzzing","Sandboxing","Honeypotting","Steganalysis"], a:1, e:"Sandboxes safely execute suspect code and record behavior (file writes, C2 callbacks) without risking production systems."},
  {d:7, q:"The BEST practice before deploying a critical security patch to production servers is to:", c:["Deploy immediately to all systems","Test the patch in a non-production environment that mirrors production","Wait 90 days for community feedback","Disable antivirus during installation"], a:1, e:"Testing catches compatibility breakage; combined with phased rollout and rollback plans it balances speed with stability."},
  {d:7, q:"Threat hunting differs from traditional monitoring because it:", c:["Waits for alerts from the SIEM","Proactively searches for indicators of compromise assuming defenses have already been bypassed","Only reviews firewall logs","Is performed exclusively by external vendors"], a:1, e:"Hunting is hypothesis-driven and proactive — analysts look for stealthy attacker activity that automated alerting missed."},
  {d:7, q:"SOAR platforms improve security operations PRIMARILY by:", c:["Replacing firewalls","Automating repetitive response tasks through playbooks","Encrypting log data","Eliminating the need for analysts"], a:1, e:"Security Orchestration, Automation and Response executes playbooks (enrich, contain, notify) automatically, cutting response time and analyst fatigue."},
  {d:7, q:"An account used by an application to authenticate to a database, which no human logs into, is BEST described as a:", c:["Guest account","Service account","Shared account","Emergency account"], a:1, e:"Service accounts authenticate machine-to-machine. They need strong credential management (vaulting, rotation) since they're rarely monitored and often over-privileged."},

  // Domain 8 — Software Development Security (11)
  {d:8, q:"A program checks a file's permissions, then opens it a moment later. An attacker swaps the file between the check and the open. This is a:", c:["Buffer overflow","TOCTOU race condition","Logic bomb","Integer overflow"], a:1, e:"Time-of-check to time-of-use flaws exploit the gap between validation and use. Fix with atomic operations and file locking."},
  {d:8, q:"Stored XSS is MORE dangerous than reflected XSS because:", c:["It requires no JavaScript","The payload persists on the server and attacks every visitor","It only affects administrators","It cannot be filtered"], a:1, e:"Stored XSS is saved (e.g., in comments or profiles) and executes for all users who view it — no phishing link required."},
  {d:8, q:"The MOST effective defense against cross-site request forgery (CSRF) is:", c:["Input length limits","Anti-CSRF tokens tied to the user session","Disabling cookies","Using GET for all state changes"], a:1, e:"Unique per-session tokens in each form/request prove the request originated from your app. SameSite cookie attributes add defense in depth."},
  {d:8, q:"In a secure SDLC, threat modeling delivers the MOST value during:", c:["The design phase","User acceptance testing","Post-deployment operations","Code freeze"], a:0, e:"Modeling threats at design time lets architects eliminate flaws before code is written — the cheapest point to fix them."},
  {d:8, q:"Which testing type analyzes an application FROM THE OUTSIDE while it runs, without source code access?", c:["SAST","DAST","SCA","Linting"], a:1, e:"Dynamic Application Security Testing probes the running app (like an attacker). SAST reads source; SCA inventories third-party components."},
  {d:8, q:"Software Composition Analysis (SCA) tools PRIMARILY address the risk of:", c:["Weak passwords","Vulnerable open-source libraries and dependencies","Poor code comments","Slow build times"], a:1, e:"Modern apps are mostly third-party code. SCA identifies known-vulnerable dependencies (e.g., Log4j) and license issues."},
  {d:8, q:"In the Capability Maturity Model, the level at which processes are quantitatively measured and controlled is:", c:["Level 2 — Repeatable/Managed","Level 3 — Defined","Level 4 — Quantitatively Managed","Level 5 — Optimizing"], a:2, e:"CMM: 1 Initial, 2 Managed/Repeatable, 3 Defined, 4 Quantitatively Managed (metrics-driven), 5 Optimizing (continuous improvement)."},
  {d:8, q:"Polyinstantiation in a multilevel-secure database is used to prevent:", c:["SQL injection","Inference and unauthorized disclosure by keeping different versions of a row at different classification levels","Deadlocks","Data duplication"], a:1, e:"Two rows with the same key but different classifications stop low-clearance users from inferring classified data from constraint violations."},
  {d:8, q:"Which language choice MOST reduces the risk of buffer overflow vulnerabilities?", c:["C","Assembly","A memory-safe language such as Rust, Java, or C#","C++ with raw pointers"], a:2, e:"Memory-safe languages enforce bounds checking and managed memory, eliminating most overflow classes that plague C/C++."},
  {d:8, q:"An API lets any authenticated user retrieve other users' records by changing the ID in the URL. This vulnerability is:", c:["Broken object level authorization (IDOR)","Cross-site scripting","Race condition","Clickjacking"], a:0, e:"BOLA/IDOR — the top API risk — occurs when object-level access checks are missing. Every request must verify the caller owns/may access the object."},
  {d:8, q:"To protect a CI/CD pipeline's integrity, the MOST important control is:", c:["Faster build agents","Signed commits and artifacts with strict access control to the pipeline","Weekly full backups","Colorful build dashboards"], a:1, e:"Pipeline compromise poisons everything downstream (supply chain attacks). Code signing, artifact verification, and least-privilege pipeline access are essential."}
];
